name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Pas aan naar 'master' als je repo die branch gebruikt

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup headers
        run: |
          mkdir -p public
          echo "/\n  Cross-Origin-Embedder-Policy: require-corp\n  Cross-Origin-Opener-Policy: same-origin" > public/_headers

      - name: Copy site
        run: cp -r index.html style.css script.js public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
